"""The application factory, and the one place middleware order is decided.

Middleware order is not a detail. Access logging is outermost so that a request rejected by auth is
still counted — a 401 you cannot see is an attack you cannot notice. And the log is installed
before anything that could raise, because the interesting failures happen in the layers below it.

Run it:  uvicorn app.api.main:app --reload
"""

from __future__ import annotations

import logging
import os

from fastapi import FastAPI

from ..infra import telemetry
from .middleware import AccessLog
from .routes import router


def configure_logging() -> None:
    """Structured-ish logging with no content in it.

    The format names the fields the access log sets and nothing else. A `%(message)s` catch-all
    format is how a carefully redacted log line gets undone by the next person who logs an
    f-string containing the request body.
    """
    logging.basicConfig(
        level=os.getenv("LOG_LEVEL", "INFO"),
        format=(
            '{"ts":"%(asctime)s","level":"%(levelname)s","event":"%(message)s",'
            '"request_id":"%(request_id)s","method":"%(method)s","route":"%(route)s",'
            '"status":%(status)s,"duration_ms":%(duration_ms)s,"tenant":"%(tenant)s"}'
        ),
    )
    # Silence the framework's own access log: it records the full path, which for
    # /v1/approvals/{id} means the identifier, and identifiers in paths are personal data in a
    # great many services. Ours logs the route template instead.
    logging.getLogger("uvicorn.access").disabled = True


def create_app() -> FastAPI:
    configure_logging()

    app = FastAPI(
        title="agentic-product",
        version="1.0.0",
        description=(
            "Operations agent. Reversible actions run alone; irreversible ones stop for a named "
            "human however capable the model is.\n\n"
            "The contract in contracts/openapi.json is generated by `agentarch sync` from the "
            "manifest — edit the manifest, not the JSON."
        ),
        # No /redoc, and docs off in production: an interactive console that issues real requests
        # against a real agent is a cost and a data-exposure surface, not documentation.
        docs_url="/docs" if os.getenv("ENV", "dev") == "dev" else None,
        redoc_url=None,
    )

    # Declared in the manifest as observability.otel.enabled; this is where the declaration
    # becomes true. Off when no collector is configured — a service that refuses to start because
    # it cannot reach a collector is worse than one that is not traced.
    live = telemetry.configure(service_name="ops-copilot", service_version="1.0.0")
    logging.getLogger("api").info(
        "tracing %s (semconv %s)",
        "enabled" if live else "not configured",
        telemetry.SEMCONV_VERSION,
        extra=_log_defaults,
    )

    app.add_middleware(AccessLog)
    app.include_router(router, prefix="/v1")
    return app


# The access-log format names specific fields, so a log call from anywhere else has to supply them.
# Without this a single logging call outside the middleware raises a KeyError inside logging itself,
# which is a genuinely confusing failure at startup.
_log_defaults = {
    "request_id": "-", "method": "-", "route": "-", "status": 0, "duration_ms": 0, "tenant": "-",
}


app = create_app()
