"""The application factory, and the one place middleware order is decided.

Middleware order is not a detail. Access logging is outermost so that a request rejected by auth is
still counted — a 401 you cannot see is an attack you cannot notice. And the log is installed
before anything that could raise, because the interesting failures happen in the layers below it.

This module is also where the chat page is served. The page is a static file and the API is the
service: the browser downloads HTML and JS from us and then calls only our own /v1 routes. There
is no route to the model provider from this process that a page could ride on, and nothing under
web/ names one — control.ai.api.no_client_side_model_access checks the second half of that, and
app/tests checks it on every run.

Run it:  uvicorn app.api.main:app --reload      then open http://localhost:8000/
"""

from __future__ import annotations

import logging
import os
import pathlib

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse

from ..infra import telemetry
from .middleware import AccessLog
from .routes import router

# Relative to the process working directory, which for this service is the project root — the same
# assumption agent/manifest.py makes about agentarch/.
WEB_DIR = pathlib.Path("web")

# The page loads exactly these. An allowlist rather than a static mount: a mounted directory serves
# whatever lands in it next, and "whatever lands in it" is not something this service reviews.
WEB_ASSETS = {"chat.js", "chat.css"}


def configure_logging() -> None:
    """Structured-ish logging with no content in it.

    The format names the fields the access log sets and nothing else. A `%(message)s` catch-all
    format is how a carefully redacted log line gets undone by the next person who logs an
    f-string containing the request body.
    """
    logging.basicConfig(
        level=os.getenv("LOG_LEVEL", "INFO"),
        format=(
            '{"ts":"%(asctime)s","level":"%(levelname)s","event":"%(message)s",'
            '"request_id":"%(request_id)s","method":"%(method)s","route":"%(route)s",'
            '"status":%(status)s,"duration_ms":%(duration_ms)s,"tenant":"%(tenant)s"}'
        ),
    )
    # Silence the framework's own access log: it records the full path, which for
    # /v1/approvals/{id} means the identifier, and identifiers in paths are personal data in a
    # great many services. Ours logs the route template instead.
    logging.getLogger("uvicorn.access").disabled = True


def create_app() -> FastAPI:
    configure_logging()

    app = FastAPI(
        title="chatbot-web",
        version="1.0.0",
        description=(
            "Customer-facing web chat. Answers from a knowledge base with citations, escalates "
            "rather than improvising, and puts every irreversible action behind a human decision "
            "— shown to that human as an approval card in the chat page itself.\n\n"
            "The contract in contracts/openapi.json is generated by `agentarch sync` from the "
            "manifest — edit the manifest, not the JSON."
        ),
        # No /redoc, and docs off in production: an interactive console that issues real requests
        # against a real agent is a cost and a data-exposure surface, not documentation.
        docs_url="/docs" if os.getenv("ENV", "dev") == "dev" else None,
        redoc_url=None,
    )

    # Declared in the manifest as observability.otel.enabled; this is where the declaration
    # becomes true. Off when no collector is configured — a service that refuses to start because
    # it cannot reach a collector is worse than one that is not traced.
    live = telemetry.configure(service_name="chatbot-web", service_version="1.0.0")
    logging.getLogger("api").info(
        "tracing %s (semconv %s)",
        "enabled" if live else "not configured",
        telemetry.SEMCONV_VERSION,
        extra=_log_defaults,
    )

    @app.get("/", include_in_schema=False)
    async def chat_page() -> FileResponse:
        """The chat UI. Static, unauthenticated and carrying no credential.

        Unauthenticated is correct here: the page is a document, not data. What it asks the
        visitor for — a token for this service — is checked on every /v1 call, which is the only
        place it can be.
        """
        return FileResponse(WEB_DIR / "index.html")

    @app.get("/web/{asset}", include_in_schema=False)
    async def web_asset(asset: str) -> FileResponse:
        if asset not in WEB_ASSETS:
            raise HTTPException(status_code=404, detail="no such asset")
        return FileResponse(WEB_DIR / asset)

    app.add_middleware(AccessLog)
    app.include_router(router, prefix="/v1")
    return app


# The access-log format names specific fields, so a log call from anywhere else has to supply them.
# Without this a single logging call outside the middleware raises a KeyError inside logging itself,
# which is a genuinely confusing failure at startup.
_log_defaults = {
    "request_id": "-", "method": "-", "route": "-", "status": 0, "duration_ms": 0, "tenant": "-",
}


app = create_app()
